//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wizard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Correo
    {
        public int idCorreo { get; set; }
        public string correo1 { get; set; }
        public string idPersona { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
