//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wizard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefono
    {
        public int idTelefono { get; set; }
        public string cedula { get; set; }
        public int telefono1 { get; set; }
        public int idCodigoPais { get; set; }
    
        public virtual Pai Pai { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
