//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Seminario.DAL.EF
{
    public partial class Auditoria
    {
        public int idAuditoria { get; set; }
        public string usuario { get; set; }
        public string tablaAfectada { get; set; }
        public string columna { get; set; }
        public string valorViejo { get; set; }
        public string valorNuevo { get; set; }
        public DateTime fecha { get; set; }
        public string accion { get; set; }
    }
}
