//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seminario.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarreraxCurso
    {
        public int idRelacion { get; set; }
        public int idCarrera { get; set; }
        public int idCurso { get; set; }
    
        public virtual Carrera Carrera { get; set; }
        public virtual Curso Curso { get; set; }
    }
}
