//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;

namespace Seminario.DAL.EF
{
    public partial class EncabezadoFactura
    {
        [SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EncabezadoFactura()
        {
            this.LineaFacturas = new HashSet<LineaFactura>();
        }
    
        public string idEncabezado { get; set; }
        public string idEstudiante { get; set; }
        public DateTime fechaPago { get; set; }
        public string direccion { get; set; }
        public double descuento { get; set; }
        public double totalPagar { get; set; }
        public double totalCobrar { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LineaFactura> LineaFacturas { get; set; }
    }
}
