//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seminario.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura_Usuario
    {
        public string Cedula { get; set; }
        public string Nombre { get; set; }
        public string Usuario { get; set; }
        public string N__de_Factura { get; set; }
        public System.DateTime Fecha_de_Pago { get; set; }
        public double Total_a_Cobrar { get; set; }
        public double Descuento { get; set; }
        public double Total_a_Pagar { get; set; }
        public int ID_de_Producto { get; set; }
        public double Pago_Realizado { get; set; }
        public string Descripcion { get; set; }
        public double Precio { get; set; }
    }
}
