//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seminario.DAL.EF
{
    public partial class LineaFactura
    {
        public int idLinea { get; set; }
        public int idProducto { get; set; }
        public double monto { get; set; }
        public double pago { get; set; }
        public string descripcion { get; set; }
        public string idEncabezado { get; set; }
    
        public virtual EncabezadoFactura EncabezadoFactura { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
